name: Build macOS app

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller beautifulsoup4

      - name: Build macOS application
        run: |
          pyinstaller -F -w -n BKbox main.py
          cd dist
          zip -r BKbox.zip BKbox.app/

      - name: Upload built app
        uses: actions/upload-artifact@v4
        with:
          name: BKbox-macos
          path: dist/BKbox.zip
